### ISSUE TITLE
Test api with urllib.request.

### ISSUE THREAD

**Issue by nqaegg** [nqaegg/plain#4]
- [x] #1 Check if slug must be unique
- [x] #2 Check if title must have less than 50 signs.
- [x] #3 Test api CRUD
